import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; 
import CartProvider from "../context/CartContext";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navbar */}
        <nav className="p-4 border-b border-zinc-800 flex justify-end">
          <Link href="/cart"className="px-5 py-2 rounded-md bg-blue-600 text-white font-medium hover:bg-blue-700 transition">
            Cart
          </Link>
        </nav>
        <CartProvider>
        {/* Page Content */}
        {children}
        </CartProvider>
      </body>
    </html>
  );
}
